
import { jsPDF } from 'jspdf';

interface LineItem {
  productName: string;
  quantity: number;
  unitPrice: number;
  discount: number;
  total: number;
}

interface DocumentData {
  id: string;
  type: 'quote' | 'invoice';
  customer: string;
  contact: string;
  email?: string;
  phone?: string;
  address?: string;
  date: string;
  validUntil?: string;
  dueDate?: string;
  lineItems: LineItem[];
  notes?: string;
  paymentTerms?: string;
}

export const generatePDF = (data: DocumentData) => {
  const pdf = new jsPDF();
  
  // Header Background
  pdf.setFillColor(37, 99, 235); // Blue-600
  pdf.rect(0, 0, 210, 50, 'F');
  
  // Company Logo Area (Placeholder - would be actual logo in production)
  pdf.setFillColor(255, 255, 255, 0.2);
  pdf.roundedRect(15, 15, 12, 12, 2, 2, 'F');
  
  // Company Header
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(28);
  pdf.setFont('helvetica', 'bold');
  pdf.text('GVS', 32, 25);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Sales Platform', 32, 32);
  
  // Document Title
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  const title = data.type === 'quote' ? 'QUOTATION' : 'INVOICE';
  pdf.text(title, 140, 25);
  
  // Reset text color for rest of document
  pdf.setTextColor(0, 0, 0);
  
  // Document Details
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`${data.type === 'quote' ? 'Quote' : 'Invoice'} #: ${data.id}`, 140, 35);
  pdf.text(`Date: ${data.date}`, 140, 42);
  
  if (data.type === 'quote' && data.validUntil) {
    pdf.text(`Valid Until: ${data.validUntil}`, 140, 49);
  }
  
  if (data.type === 'invoice' && data.dueDate) {
    pdf.text(`Due Date: ${data.dueDate}`, 140, 49);
  }
  
  // Customer Information
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Bill To:', 20, 70);
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.text(data.customer, 20, 80);
  pdf.text(data.contact, 20, 87);
  if (data.email) pdf.text(data.email, 20, 94);
  if (data.phone) pdf.text(data.phone, 20, 101);
  if (data.address) {
    const addressLines = data.address.split('\n');
    addressLines.forEach((line, index) => {
      pdf.text(line, 20, 108 + (index * 7));
    });
  }
  
  // Line Items Table Header
  const startY = 140;
  pdf.setFillColor(248, 250, 252); // Gray-50
  pdf.rect(15, startY - 5, 180, 12, 'F');
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Product/Service', 20, startY);
  pdf.text('Qty', 100, startY);
  pdf.text('Unit Price', 125, startY);
  pdf.text('Discount', 155, startY);
  pdf.text('Total', 180, startY);
  
  // Line Items
  pdf.setFont('helvetica', 'normal');
  let currentY = startY + 15;
  let grandTotal = 0;
  
  data.lineItems.forEach((item) => {
    pdf.text(item.productName, 20, currentY);
    pdf.text(item.quantity.toString(), 100, currentY);
    pdf.text(`$${item.unitPrice.toFixed(2)}`, 125, currentY);
    pdf.text(`${item.discount}%`, 155, currentY);
    pdf.text(`$${item.total.toFixed(2)}`, 180, currentY);
    grandTotal += item.total;
    currentY += 10;
  });
  
  // Subtotal and Grand Total
  pdf.setDrawColor(200, 200, 200);
  pdf.line(125, currentY + 5, 195, currentY + 5);
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Grand Total:', 155, currentY + 15);
  pdf.text(`$${grandTotal.toFixed(2)}`, 180, currentY + 15);
  
  // Payment Terms
  if (data.paymentTerms) {
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Payment Terms:', 20, currentY + 35);
    pdf.setFont('helvetica', 'normal');
    pdf.text(data.paymentTerms, 20, currentY + 42);
  }
  
  // Notes
  if (data.notes) {
    pdf.setFont('helvetica', 'bold');
    pdf.text('Notes:', 20, currentY + 55);
    pdf.setFont('helvetica', 'normal');
    const noteLines = data.notes.split('\n');
    noteLines.forEach((line, index) => {
      pdf.text(line, 20, currentY + 62 + (index * 7));
    });
  }
  
  // Footer
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by GVS Sales Platform - Professional Sales Management', 20, 280);
  
  // Download the PDF
  const fileName = `${data.type}-${data.id}.pdf`;
  pdf.save(fileName);
};
