// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihertnwcleqjteiyaihh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZXJ0bndjbGVxanRlaXlhaWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODc1NDEsImV4cCI6MjA2NDc2MzU0MX0.Nly-yNEFz1qRBoCKnYxd60uhh-R4BmNWBWt61VjA8IU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);